name: tuneatlas
description: "Global Radio Tuner. Listen Live."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  animations: ^2.1.0
  app_links: ^6.4.1
  audio_service: ^0.18.18
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.0
  rxdart: ^0.28.0
  sembast: ^3.8.5+1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  arb_dir: lib\src\core\l10n
  output_dir: lib\src\core\l10n
